spring.application.name=desafio.votacao
spring.data.mongodb.uri=mongodb+srv://ricardomateusn:HYVyCRTP4OQZMAP5@desafio.erq61bn.mongodb.net/desafio?retryWrites=true&w=majority&appName=desafio
server.port=8080
logging.level.org.springframework=INFO
logging.level.org.mongodb.driver=INFO